spring:
  application:
    name: spring-batch-with-jms

  datasource:
    url: jdbc:h2:tcp://localhost/~/test

  batch:
    job:
#      control which jobs to execute on startup, empty means all jobs
      names:
#       batch jobs are enabled by default
      enabled: false

# if you don't define it will start an embedded instance
  activemq:
    broker-url: tcp://localhost:61616
